name: Generate Pacman Game

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia Ã  meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Pacman
        uses: jasonlong/github-contribution-calendar-action@main
        with:
          github_user_name: cmensato
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
